# Generated by Django 5.0.7 on 2024-08-03 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0002_urldata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urldata',
            name='user',
        ),
    ]
