# Generated by Django 5.0.7 on 2024-08-03 14:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0003_remove_urldata_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urldata',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='urldata',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
