# Generated by Django 5.0.7 on 2024-08-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0004_alter_urldata_options_urldata_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='urldata',
            name='shorten_url',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
