# Generated by Django 5.0.7 on 2024-08-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0005_urldata_shorten_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldata',
            name='shorten_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='urldata',
            name='url',
            field=models.URLField(),
        ),
    ]
