# Generated by Django 5.0.7 on 2024-08-03 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0008_remove_urldata_shorten_url_alter_urldata_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urldata',
            options={},
        ),
        migrations.RemoveField(
            model_name='urldata',
            name='created',
        ),
        migrations.RemoveField(
            model_name='urldata',
            name='user',
        ),
    ]
